In [1]:
import cv2 

In [11]:
# https://stackoverflow.com/questions/53130370/how-to-access-phone-camera-using-python-script/53131060
import urllib.request
import cv2
import numpy as np
import ssl

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

url = 'http://10.8.112.97:8080/video'

while True:
    imgResp = urllib.request.urlopen(url)
    imgNp = np.array(bytearray(imgResp.read()), dtype=np.uint8)
    img = cv2.imdecode(imgNp, -1)
    cv2.imshow('temp',cv2.resize(img,(600,400)))
    q = cv2.waitKey(1)
    if q == ord("q"):
        break;

cv2.destroyAllWindows()

KeyboardInterrupt: 

In [2]:
import imutils

In [3]:
hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())
   

In [4]:
#image = cv2.imread('/Users/kargilthakur/Desktop/4SHUTDKWUJBQXALP7LBBUUGSXM.jpeg')
image = cv2.imread('/Users/kargilthakur/Desktop/007A2302.JPG')


In [5]:
image = imutils.resize(image,
                       width=min(400, image.shape[1]))
   

In [6]:
(regions, _) = hog.detectMultiScale(image, 
                                    winStride=(4, 4),
                                    padding=(4, 4),
                                    scale=1.05)

In [7]:
for (x, y, w, h) in regions:
    cv2.rectangle(image, (x, y), 
                  (x + w, y + h), 
                  (0, 0, 255), 2)

In [8]:
cv2.imshow("Image", image)
cv2.waitKey(3)
cv2.destroyAllWindows()


In [9]:
# import the necessary packages
import numpy as np
import cv2
from itertools import combinations
 
# initialize the HOG descriptor/person detector
hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())

cv2.startWindowThread()

# open webcam video stream
cap = cv2.VideoCapture(0)

# the output will be written to output.avi
out = cv2.VideoWriter(
    'output.avi',
    cv2.VideoWriter_fourcc(*'MJPG'),
    15.,
    (640,480))

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # resizing for faster detection
    frame = cv2.resize(frame, (640, 480))
    # using a greyscale picture, also for faster detection
    gray = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)

    # detect people in the image
    # returns the bounding boxes for the detected objects
    boxes, weights = hog.detectMultiScale(frame, winStride=(8,8) )

    boxes = np.array([[x, y, x + w, y + h] for (x, y, w, h) in boxes])
    print(len(boxes))
    print(boxes)
    
    l1=[]
    for (xA, yA, xB, yB) in boxes:
        # display the detected boxes in the colour picture
        cv2.rectangle(frame, (xA, yA), (xB, yB),
                          (0, 255, 0), 2)
        if len(boxes)>1:#for computing centroids of rectangles
            l1.append([(xA+xB)/2,(yA+yB)/2])
            
    l2=[]
    l2=combinations(l1,2)
    d1=[]#distances list
    for i in l2:
        a=i[0]
        b=i[1]
        dist=(a[0]-b[0])^2 + (a[1]-b[1])^2
        dist.append(dist)
         
    
    # Write the output video 
#     out.write(frame.astype('uint8'))
    # Display the resulting frame
#     cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
# and release the output
out.release()
# finally, close the window
cv2.destroyAllWindows()
cv2.waitKey(1)

0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
1
[[330 178 408 334]]
0
[]
1
[[342 179 416 327]]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
1
[[313 261 402 438]]
0
[]
1
[[ 97 318 170 463]]
1
[[ 99 316 171 461]]
0
[]
0
[]
0
[]
0
[]
1
[[116 284 185 422]]
0
[]
0
[]
1
[[123 271 197 417]]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
1
[[109 116 274 445]]
1
[[168 264 239 405]]
1
[[169 270 241 413]]
1
[[169 271 241 415]]
0
[]
0
[]
0
[]
0
[]
0
[]
1
[[179 227 271 410]]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
0
[]
1
[[144 230 259 460]]
0
[]
1
[[144 230 259 460]]
1
[[136 226 257 467]]


KeyboardInterrupt: 

In [2]:
#https://www.pyimagesearch.com/2020/06/01/opencv-social-distancing-detector/

In [18]:
from itertools import combinations
l2=[[23,34],[24,56],[26,67]]
l1=combinations(l2,2)
d1=[]
for i in l1:
        a=i[0]
        b=i[1]
        dist=(a[0]-b[0])^2 + (a[1]-b[1])^2
        d1.append(dist)
print(d1)

[17, 30, 11]
